[[redirects]]
  from = "/update.json"
  to = "https://data.covid19.go.id/public/api/update.json"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}

[[redirects]]
  from = "/prov.json"
  to = "https://data.covid19.go.id/public/api/prov.json"
  status = 200
  force = true
  headers = {Access-Control-Allow-Origin = "*"}